/* Banco 3 · SAA-C03 · preguntas tipo-examen en español. */
window.BANCO = (window.BANCO || []).concat([
  {
    id: "saa-081", dominio: 4, tema: "Compute Optimizer", tipo: "single",
    enunciado: "Una empresa sospecha que muchas instancias EC2 están sobredimensionadas y quiere recomendaciones de tamaño correcto (right-sizing) basadas en métricas de uso. ¿Qué servicio usar?",
    opciones: [
      "AWS Compute Optimizer.",
      "Amazon Inspector.",
      "AWS Config.",
      "Amazon Macie.",
    ],
    correctas: [0],
    explicacion: "AWS Compute Optimizer analiza métricas de utilización y recomienda el right-sizing de EC2, EBS, Lambda y ASG para reducir costos. Inspector evalúa vulnerabilidades, Config la configuración y Macie protege datos sensibles en S3.",
  },
  {
    id: "saa-082", dominio: 1, tema: "Macie", tipo: "single",
    enunciado: "Una empresa quiere descubrir y proteger automáticamente datos sensibles (PII) almacenados en buckets de S3. ¿Qué servicio usar?",
    opciones: [
      "Amazon Macie.",
      "AWS WAF.",
      "Amazon GuardDuty.",
      "AWS Shield.",
    ],
    correctas: [0],
    explicacion: "Amazon Macie usa machine learning para descubrir, clasificar y proteger datos sensibles (como PII) en S3. GuardDuty detecta amenazas, WAF filtra tráfico web y Shield protege contra DDoS.",
  },
  {
    id: "saa-083", dominio: 3, tema: "Aurora replicas", tipo: "single",
    enunciado: "Una aplicación con Aurora experimenta picos de lectura. El equipo quiere escalar las réplicas de lectura automáticamente según la carga. ¿Qué configurar?",
    opciones: [
      "Aurora Auto Scaling para réplicas de lectura.",
      "Multi-AZ en RDS estándar.",
      "Un NLB delante de la base de datos.",
      "Aumentar el tamaño del volumen.",
    ],
    correctas: [0],
    explicacion: "Aurora Auto Scaling añade o quita réplicas de lectura automáticamente según una métrica objetivo (como la CPU o las conexiones), absorbiendo los picos de lectura. Un NLB no escala una base de datos.",
  },
  {
    id: "saa-084", dominio: 2, tema: "S3 durabilidad", tipo: "single",
    enunciado: "¿Qué afirmación describe correctamente la durabilidad y disponibilidad de Amazon S3 Standard?",
    opciones: [
      "Almacena los objetos de forma redundante en múltiples AZ, ofreciendo 11 nueves de durabilidad.",
      "Guarda una sola copia en una AZ.",
      "Requiere que el cliente configure la replicación manualmente para no perder datos.",
      "Solo es durable si se activa el versionado.",
    ],
    correctas: [0],
    explicacion: "S3 Standard replica automáticamente los objetos en múltiples AZ y está diseñado para 99,999999999% (11 nueves) de durabilidad. No requiere replicación manual; el versionado protege contra borrados, no es lo que da la durabilidad base.",
  },
  {
    id: "saa-085", dominio: 3, tema: "ElastiCache Redis", tipo: "single",
    enunciado: "Una aplicación necesita una caché en memoria que soporte replicación, persistencia y conmutación por error (failover) para almacenar sesiones de usuario. ¿Qué motor de ElastiCache elegir?",
    opciones: [
      "ElastiCache for Redis.",
      "ElastiCache for Memcached.",
      "Amazon RDS.",
      "DynamoDB DAX.",
    ],
    correctas: [0],
    explicacion: "ElastiCache for Redis soporta replicación, persistencia, réplicas de lectura y failover (Multi-AZ), adecuado para sesiones que requieren durabilidad. Memcached es más simple y no ofrece replicación ni persistencia.",
  },
  {
    id: "saa-086", dominio: 1, tema: "VPC NACL vs SG", tipo: "single",
    enunciado: "Un arquitecto necesita bloquear explícitamente un rango de IP malicioso a nivel de subred completa, con reglas que puedan denegar tráfico. ¿Qué usar?",
    opciones: [
      "Network ACL (NACL) con una regla deny para ese rango.",
      "Un Security Group con una regla deny.",
      "Un IAM policy.",
      "Un registro de Route 53.",
    ],
    correctas: [0],
    explicacion: "Las NACL operan a nivel de subred y permiten reglas allow y deny (son stateless), por lo que pueden bloquear explícitamente un rango de IP. Los Security Groups solo permiten reglas allow y son stateful, no pueden denegar de forma explícita.",
  },
  {
    id: "saa-087", dominio: 4, tema: "Snowball", tipo: "single",
    enunciado: "Una empresa debe transferir 80 TB de datos a AWS, pero su conexión a Internet es lenta y tardaría meses por la red. ¿Qué solución es más eficiente?",
    opciones: [
      "AWS Snowball.",
      "Subir por Internet con multipart upload.",
      "AWS Direct Connect de 50 Mbps.",
      "S3 Transfer Acceleration.",
    ],
    correctas: [0],
    explicacion: "AWS Snowball envía dispositivos físicos para transferir grandes volúmenes (decenas de TB) cuando la red no es viable o sería demasiado lenta. Para 80 TB con poca banda, Snowball es lo más rápido y rentable.",
  },
  {
    id: "saa-088", dominio: 2, tema: "Lambda concurrencia", tipo: "single",
    enunciado: "Una función Lambda crítica debe garantizar siempre cierta capacidad de ejecución inmediata sin latencia de arranque en frío durante los picos. ¿Qué configurar?",
    opciones: [
      "Provisioned Concurrency.",
      "Reducir el tiempo de espera (timeout).",
      "Aumentar la memoria al máximo.",
      "Reserved Instances.",
    ],
    correctas: [0],
    explicacion: "Provisioned Concurrency mantiene instancias de la función inicializadas y listas, eliminando los cold starts para una capacidad garantizada. Aumentar memoria ayuda al rendimiento pero no elimina los arranques en frío.",
  },
  {
    id: "saa-089", dominio: 3, tema: "QuickSight", tipo: "single",
    enunciado: "Un equipo de negocio necesita crear dashboards y visualizaciones interactivas sobre datos en Redshift y S3, de forma gestionada y serverless. ¿Qué servicio usar?",
    opciones: [
      "Amazon QuickSight.",
      "Amazon Athena.",
      "AWS Glue.",
      "Amazon EMR.",
    ],
    correctas: [0],
    explicacion: "Amazon QuickSight es el servicio de BI gestionado para crear dashboards y visualizaciones a partir de múltiples fuentes (Redshift, S3, RDS, etc.). Athena consulta con SQL, Glue hace ETL y EMR procesa big data.",
  },
  {
    id: "saa-090", dominio: 1, tema: "Direct Connect cifrado", tipo: "single",
    enunciado: "Una empresa tiene AWS Direct Connect hacia su VPC, pero la normativa exige que el tráfico esté cifrado en tránsito. ¿Cómo cumplirlo?",
    opciones: [
      "Ejecutar una VPN IPsec sobre la conexión Direct Connect.",
      "Direct Connect ya cifra todo por defecto.",
      "Usar un Internet Gateway.",
      "Habilitar el versionado de S3.",
    ],
    correctas: [0],
    explicacion: "Direct Connect por sí solo no cifra el tráfico; para cumplir el requisito se ejecuta una VPN IPsec sobre la conexión (o se usa MACsec donde esté disponible). El IGW y el versionado no tienen relación con el cifrado en tránsito del enlace.",
  },
  {
    id: "saa-091", dominio: 3, tema: "EMR", tipo: "single",
    enunciado: "Una empresa procesa grandes volúmenes de datos con frameworks como Apache Spark y Hadoop y quiere un servicio gestionado para ello. ¿Qué usar?",
    opciones: [
      "Amazon EMR.",
      "Amazon RDS.",
      "AWS Lambda.",
      "Amazon DynamoDB.",
    ],
    correctas: [0],
    explicacion: "Amazon EMR es la plataforma gestionada de big data para ejecutar Spark, Hadoop, Hive, etc., a gran escala. RDS/DynamoDB son bases de datos y Lambda no es adecuado para procesamiento masivo de larga duración.",
  },
  {
    id: "saa-092", dominio: 2, tema: "SQS retención", tipo: "single",
    enunciado: "Un consumidor estará caído por mantenimiento durante varias horas y la empresa no quiere perder los mensajes que lleguen mientras tanto. ¿Qué característica de SQS ayuda?",
    opciones: [
      "El período de retención de mensajes de SQS (hasta 14 días).",
      "Eliminar la cola y recrearla después.",
      "Reducir el visibility timeout a cero.",
      "Cambiar a SNS sin suscriptores.",
    ],
    correctas: [0],
    explicacion: "SQS retiene los mensajes hasta 14 días (por defecto 4), por lo que el consumidor puede procesarlos cuando vuelva, sin pérdida. SNS, en cambio, descarta los mensajes si no hay suscriptores que los reciban.",
  },
  {
    id: "saa-093", dominio: 4, tema: "S3 One Zone-IA", tipo: "single",
    enunciado: "Una empresa almacena copias secundarias y fácilmente regenerables a las que accede con poca frecuencia, y quiere el menor costo aun aceptando menor resiliencia. ¿Qué clase S3 usar?",
    opciones: [
      "S3 One Zone-IA.",
      "S3 Standard.",
      "S3 Standard-IA.",
      "S3 Glacier Instant Retrieval.",
    ],
    correctas: [0],
    explicacion: "S3 One Zone-IA almacena los datos en una sola AZ, costando menos que Standard-IA, y es apropiado para datos de acceso infrecuente y fácilmente recreables donde se acepta menor resiliencia. Standard-IA replica en varias AZ (más caro).",
  },
  {
    id: "saa-094", dominio: 3, tema: "Enhanced Networking", tipo: "single",
    enunciado: "Una aplicación de red intensiva necesita el mayor throughput de red posible entre instancias EC2. Además de un Cluster Placement Group, ¿qué característica de red conviene habilitar?",
    opciones: [
      "Enhanced Networking (ENA) / Elastic Fabric Adapter.",
      "Un NAT Gateway adicional.",
      "Más volúmenes EBS.",
      "Un segundo Internet Gateway.",
    ],
    correctas: [0],
    explicacion: "Enhanced Networking (ENA) y, para HPC, Elastic Fabric Adapter (EFA) ofrecen mayor ancho de banda, menor latencia y menos jitter entre instancias. Los NAT/IGW y los volúmenes EBS no mejoran el throughput de red entre instancias.",
  },
  {
    id: "saa-095", dominio: 1, tema: "STS AssumeRole", tipo: "single",
    enunciado: "Una cuenta A necesita permitir que recursos de la cuenta B accedan temporalmente a algunos de sus recursos, sin compartir credenciales permanentes. ¿Qué mecanismo usar?",
    opciones: [
      "Roles IAM entre cuentas con AWS STS (AssumeRole).",
      "Compartir las access keys del usuario root de la cuenta A.",
      "Hacer públicos los recursos.",
      "Crear un usuario IAM con contraseña fija en la cuenta B.",
    ],
    correctas: [0],
    explicacion: "El acceso cross-account se hace con roles IAM que la cuenta B asume vía STS (AssumeRole), obteniendo credenciales temporales sin compartir claves permanentes. Compartir claves root o hacer recursos públicos es inseguro.",
  },
  {
    id: "saa-096", dominio: 2, tema: "Multi-Region S3", tipo: "single",
    enunciado: "Una aplicación crítica necesita que sus objetos en S3 estén disponibles en otra región para recuperación ante desastres y para servir a usuarios de esa región con menor latencia. ¿Qué configurar?",
    opciones: [
      "S3 Cross-Region Replication (CRR).",
      "S3 Same-Region Replication (SRR).",
      "S3 Transfer Acceleration.",
      "S3 Object Lock.",
    ],
    correctas: [0],
    explicacion: "Cross-Region Replication copia automáticamente los objetos a un bucket en otra región, útil para DR y para reducir latencia de usuarios remotos. SRR replica en la misma región; Object Lock impone retención WORM.",
  },
  {
    id: "saa-097", dominio: 3, tema: "Lambda S3 trigger", tipo: "single",
    enunciado: "Cada vez que se sube una imagen a S3 debe generarse automáticamente una miniatura. ¿Cuál es la arquitectura serverless adecuada?",
    opciones: [
      "Configurar una notificación de eventos de S3 que invoque una función Lambda que cree la miniatura.",
      "Hacer polling con una instancia EC2 cada minuto.",
      "Usar AWS Batch programado cada hora.",
      "Procesar manualmente las imágenes.",
    ],
    correctas: [0],
    explicacion: "Las notificaciones de eventos de S3 pueden disparar una función Lambda al subir un objeto, generando la miniatura de inmediato y de forma serverless. El polling con EC2 o los batch programados añaden costo y latencia innecesarios.",
  },
  {
    id: "saa-098", dominio: 4, tema: "Transferencia datos", tipo: "single",
    enunciado: "Una empresa quiere reducir los costos de transferencia de datos salientes (egress) al servir contenido estático a millones de usuarios. ¿Qué enfoque ayuda?",
    opciones: [
      "Servir el contenido a través de CloudFront para reducir el egress directo desde el origen.",
      "Aumentar el tamaño de las instancias EC2.",
      "Servir todo directamente desde S3 sin CDN.",
      "Usar más NAT Gateways.",
    ],
    correctas: [0],
    explicacion: "CloudFront cachea en el borde y suele reducir el costo y el volumen de transferencia saliente desde el origen, además de mejorar el rendimiento. Servir directo desde el origen o agregar NAT Gateways no reduce el egress.",
  },
  {
    id: "saa-099", dominio: 2, tema: "Stateless sesiones", tipo: "single",
    enunciado: "Para que una aplicación web escale horizontalmente sin perder sesiones de usuario cuando se agregan o quitan instancias, ¿dónde conviene guardar el estado de sesión?",
    opciones: [
      "En un almacén externo compartido como ElastiCache o DynamoDB.",
      "En la memoria local de cada instancia.",
      "En el disco efímero de la instancia.",
      "En una sola instancia 'maestra'.",
    ],
    correctas: [0],
    explicacion: "Guardar el estado de sesión en un almacén externo (ElastiCache, DynamoDB) hace la capa de aplicación stateless, de modo que cualquier instancia puede atender cualquier solicitud y escalar sin perder sesiones. La memoria/disco local rompe la sesión al cambiar de instancia.",
  },
  {
    id: "saa-100", dominio: 1, tema: "Inspector", tipo: "single",
    enunciado: "Una empresa quiere evaluar de forma continua y automatizada las vulnerabilidades de software y la exposición de red en sus instancias EC2 y contenedores. ¿Qué servicio usar?",
    opciones: [
      "Amazon Inspector.",
      "AWS Config.",
      "Amazon Macie.",
      "AWS CloudTrail.",
    ],
    correctas: [0],
    explicacion: "Amazon Inspector evalúa automáticamente vulnerabilidades de software (CVE) y exposición de red en EC2, contenedores (ECR) y Lambda. Config evalúa cumplimiento de configuración, Macie protege datos en S3 y CloudTrail audita API.",
  },
  {
    id: "saa-101", dominio: 3, tema: "Kinesis Firehose", tipo: "single",
    enunciado: "Una empresa quiere entregar datos de streaming directamente a S3, Redshift o OpenSearch con la mínima administración y casi sin código. ¿Qué servicio usar?",
    opciones: [
      "Amazon Kinesis Data Firehose.",
      "Amazon Kinesis Data Streams con consumidores propios.",
      "Amazon SQS.",
      "AWS Glue.",
    ],
    correctas: [0],
    explicacion: "Kinesis Data Firehose entrega streaming de forma totalmente gestionada a destinos como S3, Redshift y OpenSearch, con buffering, transformación opcional y sin administrar infraestructura. Data Streams requiere construir los consumidores.",
  },
  {
    id: "saa-102", dominio: 4, tema: "EBS gp3", tipo: "single",
    enunciado: "Una empresa usa volúmenes gp2 y quiere reducir costos y poder ajustar IOPS y throughput de forma independiente del tamaño. ¿A qué tipo de volumen conviene migrar?",
    opciones: [
      "gp3.",
      "io2 Block Express.",
      "st1.",
      "sc1.",
    ],
    correctas: [0],
    explicacion: "gp3 es más económico que gp2 y permite configurar IOPS y throughput de forma independiente del tamaño del volumen. io2 es más caro (para IOPS muy altas) y st1/sc1 son HDD para throughput/archivado.",
  },
  {
    id: "saa-103", dominio: 2, tema: "Disaster Recovery Pilot Light", tipo: "single",
    enunciado: "Una empresa quiere una estrategia de DR que mantenga en otra región una copia mínima de los sistemas centrales (como la base de datos replicada) lista para escalar rápidamente ante un desastre, con costo moderado. ¿Cuál es?",
    opciones: [
      "Pilot Light.",
      "Backup & Restore.",
      "Multi-Site Active/Active.",
      "Single-AZ.",
    ],
    correctas: [0],
    explicacion: "En Pilot Light, los componentes críticos (como la base de datos) se mantienen replicados y mínimamente activos en la región de DR y el resto se levanta cuando se necesita, equilibrando costo y RTO. Backup & Restore es más lento; Active/Active es más caro.",
  },
  {
    id: "saa-104", dominio: 3, tema: "AMI golden", tipo: "single",
    enunciado: "Para que las instancias lanzadas por un Auto Scaling Group arranquen rápido y ya configuradas, evitando largos scripts de instalación en cada arranque, ¿qué conviene usar?",
    opciones: [
      "Una AMI personalizada (golden image) con el software preinstalado.",
      "Instalar todo con user data en cada arranque.",
      "Una instancia más grande.",
      "Un volumen EBS más rápido.",
    ],
    correctas: [0],
    explicacion: "Una AMI personalizada con el software ya instalado reduce el tiempo de arranque y elimina dependencias de instalación en tiempo de boot, ideal para escalado rápido. Hacer toda la instalación con user data alarga el arranque.",
  },
  {
    id: "saa-105", dominio: 1, tema: "S3 presigned", tipo: "single",
    enunciado: "Una aplicación necesita dar a un usuario acceso temporal para descargar un objeto privado de S3 durante 15 minutos, sin hacerlo público. ¿Qué mecanismo usar?",
    opciones: [
      "Una URL prefirmada (presigned URL) de S3.",
      "Hacer el objeto público temporalmente.",
      "Crear un usuario IAM para el usuario final.",
      "Compartir las claves de la cuenta.",
    ],
    correctas: [0],
    explicacion: "Una presigned URL otorga acceso temporal y limitado a un objeto privado por un tiempo definido, sin exponerlo públicamente ni crear credenciales nuevas. Hacer el objeto público o compartir claves viola la seguridad.",
  },
  {
    id: "saa-106", dominio: 2, tema: "Auto Scaling lifecycle", tipo: "single",
    enunciado: "Una empresa necesita ejecutar una acción (drenar conexiones / guardar logs) justo antes de que el Auto Scaling Group termine una instancia. ¿Qué característica usar?",
    opciones: [
      "Lifecycle Hooks del Auto Scaling Group.",
      "Scheduled Scaling.",
      "Target Tracking.",
      "Spot Fleet.",
    ],
    correctas: [0],
    explicacion: "Los Lifecycle Hooks pausan la instancia en estados de lanzamiento o terminación para ejecutar acciones personalizadas (drenar conexiones, copiar logs) antes de continuar. Las políticas de escalado no permiten esa pausa controlada.",
  },
  {
    id: "saa-107", dominio: 4, tema: "Tags costos", tipo: "single",
    enunciado: "Una empresa quiere asignar y analizar los costos de AWS por equipo y proyecto. ¿Qué práctica habilita ese análisis en Cost Explorer?",
    opciones: [
      "Usar cost allocation tags (etiquetas de asignación de costos) en los recursos.",
      "Crear una cuenta nueva por cada gasto.",
      "Revisar manualmente cada factura.",
      "Desactivar el detalle de facturación.",
    ],
    correctas: [0],
    explicacion: "Las cost allocation tags permiten categorizar recursos (por equipo, proyecto, entorno) y luego filtrar/agrupar los costos en Cost Explorer y los informes de facturación. Revisar facturas manualmente no escala.",
  },
  {
    id: "saa-108", dominio: 3, tema: "OpenSearch", tipo: "single",
    enunciado: "Una empresa necesita buscar y analizar grandes volúmenes de logs en tiempo casi real con capacidades de búsqueda de texto completo y dashboards. ¿Qué servicio usar?",
    opciones: [
      "Amazon OpenSearch Service.",
      "Amazon RDS.",
      "Amazon S3 Glacier.",
      "AWS Lambda.",
    ],
    correctas: [0],
    explicacion: "Amazon OpenSearch Service está diseñado para búsqueda de texto completo, análisis de logs y observabilidad con dashboards (Kibana/OpenSearch Dashboards). RDS es relacional, Glacier es archivado y Lambda es cómputo por eventos.",
  },
  {
    id: "saa-109", dominio: 2, tema: "Transit Gateway", tipo: "single",
    enunciado: "Una empresa tiene decenas de VPC y redes on-premises que necesitan interconectarse de forma centralizada y escalable, evitando una malla compleja de VPC Peering. ¿Qué servicio usar?",
    opciones: [
      "AWS Transit Gateway.",
      "VPC Peering entre todas las VPC.",
      "Un NAT Gateway compartido.",
      "Internet Gateway.",
    ],
    correctas: [0],
    explicacion: "Transit Gateway actúa como un hub central que conecta muchas VPC y redes on-premises de forma escalable, eliminando la malla full-mesh de peerings. El VPC Peering no es transitivo y se vuelve inmanejable a gran escala.",
  },
  {
    id: "saa-110", dominio: 1, tema: "Config", tipo: "single",
    enunciado: "Una empresa quiere evaluar continuamente si sus recursos cumplen reglas de configuración (por ejemplo, 'todos los buckets S3 deben estar cifrados') y registrar los cambios de configuración. ¿Qué servicio usar?",
    opciones: [
      "AWS Config con reglas de cumplimiento.",
      "AWS CloudTrail.",
      "Amazon CloudWatch.",
      "AWS Trusted Advisor.",
    ],
    correctas: [0],
    explicacion: "AWS Config registra el historial de configuración de los recursos y evalúa el cumplimiento frente a reglas (managed o personalizadas), como exigir cifrado en S3. CloudTrail audita llamadas a la API, no el cumplimiento de configuración.",
  },
  {
    id: "saa-111", dominio: 3, tema: "DataSync", tipo: "single",
    enunciado: "Una empresa necesita transferir y sincronizar grandes cantidades de datos entre un NAS on-premises y Amazon S3/EFS de forma periódica, rápida y automatizada. ¿Qué servicio usar?",
    opciones: [
      "AWS DataSync.",
      "AWS Snowmobile.",
      "S3 Transfer Acceleration.",
      "AWS Backup.",
    ],
    correctas: [0],
    explicacion: "AWS DataSync automatiza y acelera la transferencia y sincronización de datos entre on-premises y servicios AWS (S3, EFS, FSx), con programación y verificación de integridad. Snowmobile es para migraciones masivas únicas a escala de exabytes.",
  },
  {
    id: "saa-112", dominio: 4, tema: "RDS reserved", tipo: "single",
    enunciado: "Una base de datos RDS de producción funcionará de forma constante durante al menos un año. ¿Cómo reducir su costo respecto a On-Demand?",
    opciones: [
      "Comprar RDS Reserved Instances.",
      "Usar Spot para RDS.",
      "Cambiar a una instancia más grande On-Demand.",
      "Habilitar Multi-AZ.",
    ],
    correctas: [0],
    explicacion: "Las RDS Reserved Instances reducen significativamente el costo de bases de datos con uso constante a 1 o 3 años. RDS no ofrece precios Spot; Multi-AZ mejora disponibilidad pero aumenta el costo.",
  },
  {
    id: "saa-113", dominio: 2, tema: "ALB sticky", tipo: "single",
    enunciado: "Una aplicación legada guarda el estado de sesión en la propia instancia y, mientras se migra a una arquitectura stateless, necesita que cada usuario siga llegando a la misma instancia. ¿Qué configurar en el ALB?",
    opciones: [
      "Sticky sessions (afinidad de sesión) en el target group.",
      "Quitar el balanceador de carga.",
      "Cross-Zone Load Balancing.",
      "Un NLB en lugar del ALB.",
    ],
    correctas: [0],
    explicacion: "Las sticky sessions del ALB usan una cookie para enviar a cada usuario siempre a la misma instancia, lo que mantiene funcionando una app con estado local de forma temporal. La solución definitiva es externalizar la sesión (stateless).",
  },
  {
    id: "saa-114", dominio: 1, tema: "KMS rotación", tipo: "single",
    enunciado: "Una empresa quiere que sus claves de cifrado administradas por el cliente en KMS roten automáticamente cada año para cumplir políticas de seguridad. ¿Qué hacer?",
    opciones: [
      "Habilitar la rotación automática anual de la KMS key.",
      "Crear manualmente una clave nueva cada año y reescribir todo.",
      "Usar SSE-S3 en lugar de KMS.",
      "Deshabilitar el cifrado.",
    ],
    correctas: [0],
    explicacion: "AWS KMS permite habilitar la rotación automática de claves administradas por el cliente (anual), sin reescribir los datos, manteniendo el material antiguo para descifrar lo previo. La rotación manual es propensa a errores.",
  },
  {
    id: "saa-115", dominio: 3, tema: "Write scaling", tipo: "single",
    enunciado: "Una aplicación tiene una carga de ESCRITURA muy alta sobre una base de datos relacional y la instancia única no da abasto. Las Read Replicas no ayudan. ¿Qué estrategia escala las escrituras?",
    opciones: [
      "Particionar/sharding los datos o usar una base de datos diseñada para escalar escrituras (por ejemplo, DynamoDB).",
      "Agregar más Read Replicas.",
      "Activar Multi-AZ.",
      "Aumentar el período de retención de backups.",
    ],
    correctas: [0],
    explicacion: "Las Read Replicas solo escalan lecturas. Para escalar escrituras se recurre a sharding/particionamiento o a una base diseñada para alto throughput de escritura distribuida como DynamoDB. Multi-AZ es disponibilidad, no escalado de escritura.",
  },
  {
    id: "saa-116", dominio: 2, tema: "CloudFront origin failover", tipo: "single",
    enunciado: "Una empresa quiere que CloudFront sirva contenido desde un origen secundario si el origen principal deja de responder. ¿Qué característica usar?",
    opciones: [
      "Origin Groups con origin failover en CloudFront.",
      "Sticky sessions.",
      "Un segundo Internet Gateway.",
      "S3 Object Lock.",
    ],
    correctas: [0],
    explicacion: "CloudFront permite definir Origin Groups con failover: si el origen primario devuelve errores, sirve desde el secundario, mejorando la resiliencia. Las otras opciones no tienen relación con el failover de orígenes.",
  },
  {
    id: "saa-117", dominio: 4, tema: "Serverless costo", tipo: "single",
    enunciado: "Una aplicación nueva tiene tráfico muy variable y el equipo quiere evitar costos fijos y administración de servidores, pagando solo por uso real. ¿Qué pila arquitectónica conviene?",
    opciones: [
      "API Gateway + Lambda + DynamoDB On-Demand.",
      "EC2 + RDS Multi-AZ encendidos 24/7.",
      "EKS con nodos reservados.",
      "Un mainframe en Outposts.",
    ],
    correctas: [0],
    explicacion: "Una arquitectura serverless (API Gateway + Lambda + DynamoDB On-Demand) escala con la demanda y cobra por uso, eliminando costos fijos y administración de servidores, ideal para tráfico variable. EC2/RDS/EKS dedicados implican costo constante.",
  },
  {
    id: "saa-118", dominio: 1, tema: "Parameter Store", tipo: "single",
    enunciado: "Una aplicación necesita almacenar parámetros de configuración (no secretos críticos) de forma gratuita y centralizada, con la opción de cifrar algunos valores. ¿Qué servicio usar?",
    opciones: [
      "AWS Systems Manager Parameter Store.",
      "Amazon S3 con objetos públicos.",
      "Variables de entorno en cada instancia.",
      "Un archivo en un repositorio Git.",
    ],
    correctas: [0],
    explicacion: "Parameter Store almacena configuración y secretos de forma centralizada y jerárquica, con parámetros String y SecureString (cifrados con KMS), y su nivel estándar es gratuito. Guardar config en Git o en objetos públicos es inseguro y difícil de mantener.",
  },
  {
    id: "saa-119", dominio: 2, tema: "RTO RPO", tipo: "single",
    enunciado: "Una empresa define que, tras un desastre, puede tolerar como máximo 5 minutos de pérdida de datos y 30 minutos para volver a estar operativa. Estos valores corresponden, respectivamente, a:",
    opciones: [
      "RPO de 5 minutos y RTO de 30 minutos.",
      "RTO de 5 minutos y RPO de 30 minutos.",
      "Ambos son el RTO.",
      "Ambos son el RPO.",
    ],
    correctas: [0],
    explicacion: "El RPO (Recovery Point Objective) es la máxima pérdida de datos aceptable (5 min) y el RTO (Recovery Time Objective) es el tiempo máximo para restaurar el servicio (30 min). Distinguir RPO/RTO ayuda a elegir la estrategia de DR adecuada.",
  },
  {
    id: "saa-120", dominio: 3, tema: "Decoupling escalado", tipo: "multiple",
    enunciado: "Una aplicación de procesamiento de imágenes recibe ráfagas impredecibles de trabajos. ¿Qué dos elementos permiten escalar el procesamiento de forma elástica y resiliente? (Elegí 2).",
    opciones: [
      "Una cola SQS que almacene los trabajos entrantes.",
      "Un Auto Scaling Group de workers que escale según la profundidad de la cola.",
      "Una única instancia EC2 grande procesando todo en serie.",
      "Guardar los trabajos en la memoria local del frontend.",
    ],
    correctas: [0, 1],
    explicacion: "Colocar los trabajos en SQS desacopla la recepción del procesamiento, y un ASG que escale según la cantidad de mensajes en la cola añade o quita workers según la demanda real, logrando elasticidad y resiliencia. Una sola instancia en serie no escala y la memoria local pierde trabajos ante fallos.",
  },
]);
