/* Banco 1 · SAA-C03 · preguntas tipo-examen en español.
   correctas = índices 0-based sobre el orden original de "opciones". */
window.BANCO = (window.BANCO || []).concat([
  {
    id: "saa-001", dominio: 1, tema: "IAM", tipo: "single",
    enunciado: "Una aplicación que corre en una instancia EC2 necesita leer objetos de un bucket de Amazon S3. ¿Cuál es la forma MÁS segura de otorgar ese acceso?",
    opciones: [
      "Guardar las claves de acceso de un usuario IAM en un archivo de configuración en la instancia.",
      "Asignar a la instancia EC2 un IAM Role con una política que permita s3:GetObject sobre ese bucket.",
      "Hacer el bucket público y filtrar por la IP de la instancia.",
      "Incrustar las credenciales del usuario root en variables de entorno.",
    ],
    correctas: [1],
    explicacion: "Los IAM Roles entregan credenciales temporales y rotadas automáticamente a la instancia, sin claves en el código ni en disco. Guardar access keys (A, D) es inseguro y difícil de rotar. Hacer el bucket público (C) expone los datos.",
  },
  {
    id: "saa-002", dominio: 1, tema: "S3", tipo: "single",
    enunciado: "Una empresa necesita cumplir una normativa que exige que ciertos objetos en S3 no puedan ser eliminados ni modificados durante 7 años. ¿Qué característica cumple este requisito?",
    opciones: [
      "S3 Versioning.",
      "S3 Lifecycle policies.",
      "S3 Object Lock en modo Compliance.",
      "S3 Cross-Region Replication.",
    ],
    correctas: [2],
    explicacion: "S3 Object Lock (WORM) en modo Compliance impide borrar o sobrescribir un objeto hasta que pase el período de retención, incluso para el usuario root. Versioning ayuda contra borrados accidentales pero no impone retención inmutable. Lifecycle y CRR no bloquean modificaciones.",
  },
  {
    id: "saa-003", dominio: 2, tema: "RDS", tipo: "single",
    enunciado: "Una base de datos Amazon RDS MySQL debe seguir disponible automáticamente si falla la zona de disponibilidad donde está el nodo primario, con mínima interrupción. ¿Qué configuración usar?",
    opciones: [
      "Crear varias Read Replicas en la misma AZ.",
      "Habilitar el despliegue Multi-AZ de RDS.",
      "Tomar snapshots manuales cada hora.",
      "Migrar a una instancia EC2 con MySQL autoadministrado.",
    ],
    correctas: [1],
    explicacion: "RDS Multi-AZ mantiene una réplica síncrona en otra AZ y hace failover automático ante fallo del primario. Las Read Replicas escalan lecturas, no dan failover automático sincrónico. Los snapshots sirven para restaurar, no para alta disponibilidad inmediata.",
  },
  {
    id: "saa-004", dominio: 3, tema: "RDS", tipo: "single",
    enunciado: "Una aplicación de lectura intensiva sobre Amazon RDS sufre lentitud por la gran cantidad de consultas de solo lectura (reportes). ¿Cuál es la mejor solución para escalar las lecturas?",
    opciones: [
      "Activar Multi-AZ.",
      "Agregar Read Replicas y dirigir las consultas de lectura hacia ellas.",
      "Aumentar el tamaño del volumen de almacenamiento.",
      "Convertir la base de datos a S3.",
    ],
    correctas: [1],
    explicacion: "Las Read Replicas descargan el tráfico de lectura del primario y permiten escalar horizontalmente las lecturas. Multi-AZ es para disponibilidad, no para escalar lecturas. Más almacenamiento no resuelve la carga de CPU/consultas.",
  },
  {
    id: "saa-005", dominio: 2, tema: "SQS", tipo: "single",
    enunciado: "Una aplicación web envía tareas a un backend que a veces se satura durante picos de tráfico, provocando pérdida de solicitudes. ¿Qué servicio ayuda a desacoplar los componentes y absorber los picos?",
    opciones: [
      "Amazon SNS con suscripción por email.",
      "Amazon SQS como cola entre el frontend y el backend.",
      "Amazon CloudFront delante del backend.",
      "AWS Direct Connect.",
    ],
    correctas: [1],
    explicacion: "Amazon SQS desacopla productor y consumidor: el frontend encola mensajes y el backend los procesa a su ritmo, absorbiendo picos sin perder solicitudes. SNS es pub/sub (no buffer de trabajo), CloudFront es CDN y Direct Connect es conectividad de red.",
  },
  {
    id: "saa-006", dominio: 3, tema: "DynamoDB", tipo: "single",
    enunciado: "Una aplicación de juegos requiere una base de datos NoSQL totalmente gestionada, con latencia de un solo dígito en milisegundos y escalado sin administrar servidores. ¿Qué servicio elegir?",
    opciones: [
      "Amazon RDS para PostgreSQL.",
      "Amazon Redshift.",
      "Amazon DynamoDB.",
      "Amazon Aurora MySQL.",
    ],
    correctas: [2],
    explicacion: "DynamoDB es NoSQL totalmente gestionado, con latencia de milisegundos de un dígito y escalado automático sin servidores. Redshift es data warehouse (analítica), y RDS/Aurora son relacionales.",
  },
  {
    id: "saa-007", dominio: 3, tema: "DynamoDB", tipo: "single",
    enunciado: "Una tabla de DynamoDB de lectura intensiva necesita reducir su latencia de milisegundos a microsegundos para lecturas repetidas. ¿Qué se debe agregar?",
    opciones: [
      "Amazon ElastiCache for Memcached.",
      "DynamoDB Accelerator (DAX).",
      "Read Replicas de DynamoDB.",
      "Amazon CloudFront.",
    ],
    correctas: [1],
    explicacion: "DAX es una caché en memoria específica para DynamoDB que lleva las lecturas a microsegundos sin cambiar el código de la aplicación. ElastiCache podría usarse pero requiere lógica adicional; DynamoDB no tiene 'Read Replicas' como tal; CloudFront es para contenido web.",
  },
  {
    id: "saa-008", dominio: 1, tema: "VPC", tipo: "single",
    enunciado: "Instancias EC2 en una subred privada necesitan descargar actualizaciones de software desde Internet, pero NO deben aceptar conexiones entrantes desde Internet. ¿Qué se debe usar?",
    opciones: [
      "Un Internet Gateway adjunto a la subred privada.",
      "Un NAT Gateway en una subred pública con ruta desde la subred privada.",
      "Un VPC Peering hacia otra VPC.",
      "Un Egress-Only Internet Gateway para IPv4.",
    ],
    correctas: [1],
    explicacion: "Un NAT Gateway (en subred pública) permite a instancias privadas iniciar tráfico saliente a Internet sin exponerlas a conexiones entrantes. El IGW haría la subred pública. El Egress-Only IGW es solo para IPv6.",
  },
  {
    id: "saa-009", dominio: 1, tema: "VPC", tipo: "single",
    enunciado: "Una aplicación en EC2 dentro de una VPC debe acceder a Amazon S3 sin que el tráfico salga a Internet, por requisitos de seguridad. ¿Qué se debe configurar?",
    opciones: [
      "Un NAT Gateway.",
      "Un Gateway VPC Endpoint para S3.",
      "Un Internet Gateway con WAF.",
      "Una VPN Site-to-Site.",
    ],
    correctas: [1],
    explicacion: "Un Gateway VPC Endpoint para S3 permite el acceso privado a S3 desde la VPC sin pasar por Internet, sin costo adicional. NAT Gateway e IGW envían el tráfico por Internet; la VPN conecta con on-premises.",
  },
  {
    id: "saa-010", dominio: 4, tema: "S3", tipo: "single",
    enunciado: "Una empresa almacena en S3 archivos de log a los que se accede con frecuencia los primeros 30 días, y rara vez después. Quieren reducir costos automáticamente. ¿Qué configurar?",
    opciones: [
      "Una política de Lifecycle que mueva los objetos a S3 Standard-IA o Glacier tras 30 días.",
      "Habilitar S3 Transfer Acceleration.",
      "Replicar el bucket a otra región.",
      "Activar el versionado del bucket.",
    ],
    correctas: [0],
    explicacion: "Las políticas de Lifecycle transicionan objetos a clases más baratas (Standard-IA, Glacier) según su antigüedad, optimizando costos automáticamente. Transfer Acceleration acelera transferencias (no ahorra), la replicación y el versionado aumentan el costo.",
  },
  {
    id: "saa-011", dominio: 2, tema: "Auto Scaling", tipo: "single",
    enunciado: "Para garantizar alta disponibilidad de una flota de instancias EC2 detrás de un Application Load Balancer, ¿qué configuración de Auto Scaling es la más adecuada?",
    opciones: [
      "Un Auto Scaling Group con instancias en una sola AZ.",
      "Un Auto Scaling Group que abarque múltiples zonas de disponibilidad (AZ).",
      "Instancias fijas sin Auto Scaling, sobredimensionadas.",
      "Un Auto Scaling Group con una sola instancia siempre encendida.",
    ],
    correctas: [1],
    explicacion: "Un ASG distribuido en varias AZ mantiene la disponibilidad aunque falle una zona, y reemplaza instancias no saludables automáticamente. Una sola AZ es un punto único de fallo; instancias fijas no se adaptan ni se autorrecuperan.",
  },
  {
    id: "saa-012", dominio: 3, tema: "ELB", tipo: "single",
    enunciado: "Una aplicación necesita enrutar el tráfico HTTP a diferentes grupos de destino según la ruta de la URL (/api hacia un servicio y /web hacia otro). ¿Qué balanceador usar?",
    opciones: [
      "Network Load Balancer.",
      "Application Load Balancer.",
      "Classic Load Balancer.",
      "Gateway Load Balancer.",
    ],
    correctas: [1],
    explicacion: "El ALB opera en capa 7 (HTTP/HTTPS) y permite enrutamiento por path y por host hacia distintos target groups. El NLB es capa 4 (TCP/UDP) y no entiende rutas; el Gateway LB es para appliances de red.",
  },
  {
    id: "saa-013", dominio: 3, tema: "ELB", tipo: "single",
    enunciado: "Una aplicación de trading necesita un balanceador de carga de capa 4 con latencia extremadamente baja, soporte para millones de solicitudes por segundo y una IP estática. ¿Qué elegir?",
    opciones: [
      "Application Load Balancer.",
      "Network Load Balancer.",
      "Amazon CloudFront.",
      "Classic Load Balancer.",
    ],
    correctas: [1],
    explicacion: "El NLB es de capa 4, ofrece latencia ultra baja, escala a millones de solicitudes por segundo y soporta IP estática/Elastic IP. El ALB es capa 7 (más latencia relativa) y CloudFront es CDN.",
  },
  {
    id: "saa-014", dominio: 4, tema: "EC2", tipo: "single",
    enunciado: "Una carga de procesamiento por lotes es tolerante a interrupciones y puede reiniciarse. La empresa quiere minimizar el costo de cómputo. ¿Qué tipo de instancias EC2 conviene?",
    opciones: [
      "On-Demand Instances.",
      "Reserved Instances.",
      "Spot Instances.",
      "Dedicated Hosts.",
    ],
    correctas: [2],
    explicacion: "Las Spot Instances ofrecen hasta ~90% de descuento y son ideales para cargas tolerantes a interrupciones (batch, procesamiento). On-Demand y Reserved son más caras; los Dedicated Hosts son para requisitos de licenciamiento/compliance.",
  },
  {
    id: "saa-015", dominio: 4, tema: "EC2", tipo: "single",
    enunciado: "Una aplicación tiene una carga base estable y predecible que correrá 24/7 durante los próximos 3 años. ¿Cómo se minimiza el costo de esas instancias EC2?",
    opciones: [
      "Usar exclusivamente Spot Instances.",
      "Comprar Reserved Instances o un Compute Savings Plan a 3 años.",
      "Mantener instancias On-Demand.",
      "Usar instancias más grandes On-Demand.",
    ],
    correctas: [1],
    explicacion: "Para cargas estables a largo plazo, las Reserved Instances o los Savings Plans (1 o 3 años) ofrecen el mayor ahorro frente a On-Demand. Spot no garantiza disponibilidad para una carga 24/7 constante.",
  },
  {
    id: "saa-016", dominio: 1, tema: "KMS", tipo: "single",
    enunciado: "Una organización necesita cifrar datos en S3 y mantener control y auditoría sobre las claves de cifrado, incluyendo rotación. ¿Qué opción usar?",
    opciones: [
      "SSE-S3 con claves gestionadas por S3.",
      "SSE-KMS con claves administradas en AWS KMS.",
      "Cifrado del lado del cliente sin gestión.",
      "No cifrar y restringir por Security Group.",
    ],
    correctas: [1],
    explicacion: "SSE-KMS usa AWS KMS, que ofrece control de acceso granular a las claves, rotación y auditoría vía CloudTrail. SSE-S3 cifra pero da menos control sobre las claves. Los Security Groups no cifran datos en reposo.",
  },
  {
    id: "saa-017", dominio: 1, tema: "Cognito", tipo: "single",
    enunciado: "Una aplicación móvil necesita gestionar el registro e inicio de sesión de miles de usuarios finales, con soporte para login social (Google, Facebook). ¿Qué servicio usar?",
    opciones: [
      "AWS IAM Users para cada usuario final.",
      "Amazon Cognito User Pools.",
      "AWS Directory Service.",
      "AWS Organizations.",
    ],
    correctas: [1],
    explicacion: "Cognito User Pools gestiona el registro/login de usuarios de aplicaciones, incluyendo federación con proveedores sociales e identidad. No se deben crear usuarios IAM para usuarios finales de una app (IAM es para acceso a recursos AWS).",
  },
  {
    id: "saa-018", dominio: 2, tema: "Route 53", tipo: "single",
    enunciado: "Una empresa quiere que, si su sitio principal falla, el tráfico DNS se redirija automáticamente a un sitio de respaldo en otra región. ¿Qué política de enrutamiento de Route 53 usar?",
    opciones: [
      "Weighted routing.",
      "Failover routing con health checks.",
      "Simple routing.",
      "Multivalue answer routing.",
    ],
    correctas: [1],
    explicacion: "La política Failover de Route 53, combinada con health checks, dirige el tráfico al recurso secundario cuando el primario deja de estar saludable. Weighted reparte por porcentajes y Simple no hace failover.",
  },
  {
    id: "saa-019", dominio: 3, tema: "CloudFront", tipo: "single",
    enunciado: "Un sitio web sirve contenido estático a usuarios de todo el mundo y sufre alta latencia en regiones lejanas al origen. ¿Qué servicio reduce la latencia cacheando el contenido cerca de los usuarios?",
    opciones: [
      "Amazon CloudFront.",
      "Amazon Route 53.",
      "AWS Global Accelerator.",
      "Elastic Load Balancing.",
    ],
    correctas: [0],
    explicacion: "CloudFront es una CDN que cachea el contenido en edge locations cercanas a los usuarios, reduciendo la latencia. Route 53 es DNS; Global Accelerator mejora apps TCP/UDP pero no cachea contenido estático.",
  },
  {
    id: "saa-020", dominio: 3, tema: "EFS", tipo: "single",
    enunciado: "Varias instancias EC2 en distintas AZ necesitan acceder simultáneamente al mismo sistema de archivos compartido tipo NFS, con escalado automático. ¿Qué servicio usar?",
    opciones: [
      "Amazon EBS multi-attach.",
      "Amazon EFS.",
      "Instance Store.",
      "Amazon FSx for Windows File Server.",
    ],
    correctas: [1],
    explicacion: "Amazon EFS es un sistema de archivos NFS totalmente gestionado, compartido por muchas instancias Linux a través de varias AZ, con escalado automático. EBS es de una sola AZ; FSx for Windows es para SMB/Windows.",
  },
  {
    id: "saa-021", dominio: 2, tema: "SNS", tipo: "single",
    enunciado: "Cuando se sube un archivo a S3, el sistema debe notificar simultáneamente a varios suscriptores (una cola SQS, una función Lambda y un email). ¿Qué patrón usar?",
    opciones: [
      "Enviar el evento a una sola cola SQS.",
      "Publicar el evento en un tópico de Amazon SNS con múltiples suscriptores (fan-out).",
      "Usar CloudFront para distribuir el evento.",
      "Escribir el evento en DynamoDB y hacer polling.",
    ],
    correctas: [1],
    explicacion: "SNS implementa pub/sub: un mensaje publicado en el tópico se entrega a todos los suscriptores (SQS, Lambda, email) a la vez (fan-out). Una sola cola SQS no permite múltiples consumidores independientes del mismo mensaje.",
  },
  {
    id: "saa-022", dominio: 1, tema: "Security Group", tipo: "single",
    enunciado: "Un administrador quiere permitir tráfico SSH a una instancia EC2 únicamente desde la red corporativa (rango de IP específico) y bloquear el resto. ¿Cuál es el enfoque correcto?",
    opciones: [
      "Configurar una regla de entrada en el Security Group que permita el puerto 22 solo desde el rango de IP corporativo.",
      "Agregar una regla deny en el Security Group para todas las demás IP.",
      "Hacer pública la instancia y confiar en el sistema operativo.",
      "Abrir el puerto 22 a 0.0.0.0/0 y usar una contraseña fuerte.",
    ],
    correctas: [0],
    explicacion: "Los Security Groups solo permiten reglas allow; al permitir el puerto 22 solo desde el rango corporativo, todo lo demás queda implícitamente bloqueado. No existen reglas 'deny' en un Security Group (eso es de las NACL). Abrir 22 a todo Internet es inseguro.",
  },
  {
    id: "saa-023", dominio: 1, tema: "WAF", tipo: "single",
    enunciado: "Una aplicación web detrás de un Application Load Balancer está siendo objetivo de ataques de inyección SQL y cross-site scripting. ¿Qué servicio mitiga estos ataques de capa de aplicación?",
    opciones: [
      "AWS Shield Standard.",
      "AWS WAF con reglas administradas.",
      "Security Groups.",
      "Amazon GuardDuty.",
    ],
    correctas: [1],
    explicacion: "AWS WAF filtra solicitudes HTTP/HTTPS y puede bloquear patrones de SQLi y XSS mediante reglas (incluidas las administradas). Shield protege contra DDoS, los Security Groups filtran por IP/puerto y GuardDuty detecta amenazas pero no bloquea peticiones web.",
  },
  {
    id: "saa-024", dominio: 4, tema: "Aurora", tipo: "single",
    enunciado: "Una aplicación tiene tráfico de base de datos impredecible, con largos períodos inactivos y picos ocasionales. Quieren pagar solo por lo que usan sin administrar capacidad. ¿Qué solución relacional conviene?",
    opciones: [
      "Amazon RDS con una instancia grande siempre encendida.",
      "Amazon Aurora Serverless v2.",
      "Una base de datos en EC2 con Auto Scaling.",
      "Amazon Redshift.",
    ],
    correctas: [1],
    explicacion: "Aurora Serverless v2 escala la capacidad automáticamente según la demanda (y reduce el gasto en períodos de baja carga), ideal para cargas intermitentes/impredecibles. Una instancia siempre encendida desperdicia recursos en los períodos inactivos.",
  },
  {
    id: "saa-025", dominio: 2, tema: "Multi-AZ", tipo: "multiple",
    enunciado: "¿Cuáles de las siguientes prácticas mejoran la disponibilidad de una aplicación web en AWS? (Elegí 2).",
    opciones: [
      "Desplegar instancias EC2 en múltiples zonas de disponibilidad detrás de un balanceador de carga.",
      "Usar un Auto Scaling Group con health checks para reemplazar instancias no saludables.",
      "Ejecutar toda la aplicación en una única instancia grande.",
      "Almacenar el estado de sesión solo en la memoria local de cada instancia.",
    ],
    correctas: [0, 1],
    explicacion: "Distribuir en varias AZ detrás de un LB elimina puntos únicos de fallo, y un ASG con health checks reemplaza instancias enfermas automáticamente. Una sola instancia es un punto único de fallo y guardar la sesión solo en memoria local rompe la app si la instancia se reemplaza.",
  },
  {
    id: "saa-026", dominio: 1, tema: "S3", tipo: "single",
    enunciado: "Un bucket de S3 con datos sensibles fue expuesto accidentalmente a Internet. ¿Cuál es la forma más efectiva de prevenir el acceso público de forma generalizada?",
    opciones: [
      "Activar S3 Block Public Access a nivel de cuenta y de bucket.",
      "Renombrar el bucket.",
      "Mover los datos a otra región.",
      "Habilitar Transfer Acceleration.",
    ],
    correctas: [0],
    explicacion: "S3 Block Public Access bloquea políticas y ACL que otorguen acceso público, a nivel de cuenta o bucket, siendo la salvaguarda principal. Renombrar o cambiar de región no impide el acceso público; Transfer Acceleration no tiene relación con permisos.",
  },
  {
    id: "saa-027", dominio: 3, tema: "ElastiCache", tipo: "single",
    enunciado: "Una aplicación web consulta repetidamente los mismos datos de una base de datos relacional, generando carga elevada. ¿Qué servicio reduce esa carga cacheando resultados en memoria?",
    opciones: [
      "Amazon ElastiCache.",
      "Amazon S3.",
      "AWS Glue.",
      "Amazon Athena.",
    ],
    correctas: [0],
    explicacion: "ElastiCache (Redis o Memcached) almacena en memoria los resultados consultados con frecuencia, reduciendo drásticamente la carga sobre la base de datos y la latencia. S3 es almacenamiento de objetos; Glue y Athena son para ETL/consultas analíticas.",
  },
  {
    id: "saa-028", dominio: 2, tema: "Backup", tipo: "single",
    enunciado: "Una empresa quiere centralizar y automatizar las copias de seguridad de EBS, RDS, DynamoDB y EFS con políticas de retención. ¿Qué servicio usar?",
    opciones: [
      "Snapshots manuales programados con scripts.",
      "AWS Backup.",
      "Amazon S3 Lifecycle.",
      "AWS DataSync.",
    ],
    correctas: [1],
    explicacion: "AWS Backup centraliza y automatiza las copias de seguridad de múltiples servicios (EBS, RDS, DynamoDB, EFS, etc.) con políticas de retención y cumplimiento. Los scripts manuales son frágiles; DataSync sincroniza datos, no gestiona backups con políticas.",
  },
  {
    id: "saa-029", dominio: 4, tema: "S3", tipo: "single",
    enunciado: "Una empresa tiene datos que deben archivarse durante años y casi nunca se recuperan; cuando se necesiten, pueden esperar hasta 12 horas. ¿Qué clase de almacenamiento minimiza el costo?",
    opciones: [
      "S3 Standard.",
      "S3 Standard-IA.",
      "S3 Glacier Deep Archive.",
      "S3 Intelligent-Tiering.",
    ],
    correctas: [2],
    explicacion: "S3 Glacier Deep Archive es la clase más económica para archivado de largo plazo con recuperación tolerable en horas. Standard y Standard-IA son más caras para datos casi nunca accedidos; Intelligent-Tiering tiene sentido cuando el patrón es desconocido, no para archivado profundo definido.",
  },
  {
    id: "saa-030", dominio: 3, tema: "Lambda", tipo: "single",
    enunciado: "Una empresa quiere ejecutar código en respuesta a eventos (por ejemplo, subir un objeto a S3) sin administrar servidores y pagando solo por el tiempo de ejecución. ¿Qué servicio usar?",
    opciones: [
      "Amazon EC2 con Auto Scaling.",
      "AWS Lambda.",
      "Amazon ECS en EC2.",
      "AWS Batch.",
    ],
    correctas: [1],
    explicacion: "AWS Lambda ejecuta código por eventos sin administrar infraestructura, cobrando por tiempo de ejecución y memoria. EC2 y ECS en EC2 requieren administrar servidores; Batch es para trabajos por lotes de larga duración.",
  },
  {
    id: "saa-031", dominio: 2, tema: "SQS", tipo: "single",
    enunciado: "Un sistema de procesamiento de pedidos requiere que los mensajes se procesen exactamente una vez y en el orden estricto en que se recibieron. ¿Qué tipo de cola SQS usar?",
    opciones: [
      "SQS Standard.",
      "SQS FIFO.",
      "SNS Standard.",
      "Kinesis Data Firehose.",
    ],
    correctas: [1],
    explicacion: "Las colas SQS FIFO garantizan orden estricto y entrega exactamente una vez (sin duplicados). Las colas Standard ofrecen orden de mejor esfuerzo y posible duplicación. SNS no es una cola de trabajo y Firehose es para entrega de streaming.",
  },
  {
    id: "saa-032", dominio: 1, tema: "Secrets Manager", tipo: "single",
    enunciado: "Una aplicación necesita almacenar la contraseña de una base de datos de forma segura y rotarla automáticamente cada 30 días. ¿Qué servicio usar?",
    opciones: [
      "AWS Systems Manager Parameter Store como texto plano.",
      "AWS Secrets Manager con rotación automática.",
      "Un archivo cifrado en S3.",
      "Variables de entorno en la instancia EC2.",
    ],
    correctas: [1],
    explicacion: "AWS Secrets Manager almacena secretos cifrados y permite rotación automática integrada (por ejemplo, credenciales de RDS). Parameter Store en texto plano no es seguro; los archivos o variables de entorno no rotan automáticamente ni ofrecen el mismo control.",
  },
  {
    id: "saa-033", dominio: 3, tema: "Kinesis", tipo: "single",
    enunciado: "Una plataforma necesita ingerir y procesar en tiempo real grandes volúmenes de datos de streaming (clics, telemetría IoT) con capacidad de reproducir los datos. ¿Qué servicio usar?",
    opciones: [
      "Amazon SQS.",
      "Amazon Kinesis Data Streams.",
      "Amazon SNS.",
      "AWS Step Functions.",
    ],
    correctas: [1],
    explicacion: "Kinesis Data Streams está diseñado para ingestión y procesamiento en tiempo real de streaming a gran escala, con retención que permite reprocesar (replay) los datos. SQS/SNS son para mensajería y no ofrecen replay de streaming de la misma manera.",
  },
  {
    id: "saa-034", dominio: 4, tema: "NAT", tipo: "single",
    enunciado: "Una empresa nota costos altos por múltiples NAT Gateways. Sus instancias privadas solo necesitan acceder a S3 y DynamoDB. ¿Cómo reducir costos manteniendo el acceso privado?",
    opciones: [
      "Usar Gateway VPC Endpoints para S3 y DynamoDB en lugar de enrutar por el NAT Gateway.",
      "Reemplazar el NAT Gateway por una instancia NAT pequeña.",
      "Mover las instancias a subredes públicas.",
      "Habilitar Transfer Acceleration.",
    ],
    correctas: [0],
    explicacion: "Los Gateway VPC Endpoints para S3 y DynamoDB no tienen costo por hora ni por transferencia y permiten el acceso privado sin pasar por el NAT Gateway, reduciendo el gasto. Mover instancias a subredes públicas reduce la seguridad.",
  },
  {
    id: "saa-035", dominio: 2, tema: "DR", tipo: "single",
    enunciado: "Una empresa requiere una estrategia de recuperación ante desastres de bajo costo, donde puede tolerar un RTO/RPO de varias horas. ¿Qué estrategia es la más económica?",
    opciones: [
      "Multi-Site Active/Active.",
      "Warm Standby.",
      "Backup & Restore.",
      "Pilot Light con réplica caliente.",
    ],
    correctas: [2],
    explicacion: "Backup & Restore es la estrategia de DR más barata: se restauran copias de seguridad cuando ocurre el desastre, a cambio de un RTO/RPO mayor. Active/Active y Warm Standby son más rápidas pero mucho más costosas.",
  },
  {
    id: "saa-036", dominio: 1, tema: "Organizations", tipo: "single",
    enunciado: "Una empresa con muchas cuentas AWS quiere impedir que cualquier cuenta use regiones no aprobadas, de forma centralizada. ¿Qué usar?",
    opciones: [
      "Políticas IAM en cada usuario.",
      "Service Control Policies (SCP) en AWS Organizations.",
      "Security Groups.",
      "NACLs en cada VPC.",
    ],
    correctas: [1],
    explicacion: "Las SCP de AWS Organizations imponen límites máximos de permisos a nivel de cuenta/OU de forma centralizada, por ejemplo restringiendo regiones. Las políticas IAM individuales no escalan ni garantizan cumplimiento global; SG y NACL son de red.",
  },
  {
    id: "saa-037", dominio: 3, tema: "Global Accelerator", tipo: "single",
    enunciado: "Una aplicación TCP global necesita mejorar el rendimiento y la disponibilidad enrutando a los usuarios por la red troncal de AWS hacia el endpoint regional óptimo, con IP estáticas. ¿Qué servicio usar?",
    opciones: [
      "Amazon CloudFront.",
      "AWS Global Accelerator.",
      "Amazon Route 53 latency routing.",
      "Elastic Load Balancing.",
    ],
    correctas: [1],
    explicacion: "Global Accelerator ofrece IP anycast estáticas y enruta el tráfico por la red global de AWS al endpoint sano más cercano, mejorando latencia y failover para apps TCP/UDP. CloudFront cachea contenido (HTTP) y es ideal para estático, no para todo tráfico TCP arbitrario.",
  },
  {
    id: "saa-038", dominio: 2, tema: "Aurora", tipo: "single",
    enunciado: "Una empresa quiere una base de datos relacional compatible con MySQL, con alta disponibilidad, hasta 15 réplicas de lectura y almacenamiento auto-reparable replicado en 3 AZ. ¿Qué servicio elegir?",
    opciones: [
      "Amazon RDS for MySQL en una sola AZ.",
      "Amazon Aurora MySQL-Compatible.",
      "MySQL autoadministrado en EC2.",
      "Amazon DynamoDB.",
    ],
    correctas: [1],
    explicacion: "Aurora replica el almacenamiento en 3 AZ (6 copias), soporta hasta 15 réplicas de lectura de baja latencia y ofrece alta disponibilidad gestionada, manteniendo compatibilidad con MySQL/PostgreSQL. RDS single-AZ no da esa resiliencia; DynamoDB es NoSQL.",
  },
  {
    id: "saa-039", dominio: 4, tema: "Costos", tipo: "single",
    enunciado: "El equipo financiero quiere recibir una alerta cuando el gasto mensual de AWS supere un umbral definido. ¿Qué servicio configurar?",
    opciones: [
      "AWS Cost Explorer.",
      "AWS Budgets con alertas.",
      "Amazon CloudWatch Logs.",
      "AWS Trusted Advisor.",
    ],
    correctas: [1],
    explicacion: "AWS Budgets permite definir presupuestos y enviar alertas (por email/SNS) cuando el gasto real o previsto supera el umbral. Cost Explorer analiza y visualiza costos pero su función principal no es alertar; Trusted Advisor da recomendaciones generales.",
  },
  {
    id: "saa-040", dominio: 1, tema: "CloudTrail", tipo: "single",
    enunciado: "Para auditar quién realizó cada llamada a la API de AWS (creación, borrado, cambios) en todas las cuentas, ¿qué servicio se debe habilitar?",
    opciones: [
      "Amazon CloudWatch Metrics.",
      "AWS CloudTrail.",
      "AWS Config.",
      "Amazon Inspector.",
    ],
    correctas: [1],
    explicacion: "CloudTrail registra todas las llamadas a la API (quién, qué, cuándo, desde dónde), siendo la base de la auditoría y la investigación de seguridad. CloudWatch monitorea métricas/logs operativos; Config evalúa el estado de configuración; Inspector evalúa vulnerabilidades.",
  },
]);
