/* Banco 2 · SAA-C03 · preguntas tipo-examen en español. */
window.BANCO = (window.BANCO || []).concat([
  {
    id: "saa-041", dominio: 3, tema: "API Gateway", tipo: "single",
    enunciado: "Una empresa quiere exponer una API REST totalmente gestionada que invoque funciones Lambda, con control de throttling y autenticación, sin administrar servidores. ¿Qué servicio usar?",
    opciones: [
      "Application Load Balancer apuntando a EC2.",
      "Amazon API Gateway integrado con Lambda.",
      "Amazon CloudFront con un bucket S3.",
      "AWS App Mesh.",
    ],
    correctas: [1],
    explicacion: "API Gateway es un servicio gestionado para crear y operar APIs REST/HTTP, con throttling, caché, autenticación y se integra de forma nativa con Lambda. Un ALB hacia EC2 implica administrar servidores; CloudFront+S3 es para contenido estático.",
  },
  {
    id: "saa-042", dominio: 2, tema: "EBS", tipo: "single",
    enunciado: "Una empresa necesita proteger los datos de un volumen EBS ante el fallo de una AZ y poder restaurarlos en otra región. ¿Qué enfoque usar?",
    opciones: [
      "Crear snapshots de EBS (que se almacenan en S3) y copiarlos a otra región.",
      "Confiar en que EBS replica automáticamente entre regiones.",
      "Usar Instance Store en lugar de EBS.",
      "Aumentar el tamaño del volumen.",
    ],
    correctas: [0],
    explicacion: "Los snapshots de EBS se guardan de forma durable en S3 y pueden copiarse a otra región para recuperación ante desastres. EBS no se replica automáticamente entre regiones; Instance Store es efímero.",
  },
  {
    id: "saa-043", dominio: 3, tema: "FSx", tipo: "single",
    enunciado: "Una aplicación Windows necesita un sistema de archivos compartido con soporte SMB e integración con Active Directory. ¿Qué servicio elegir?",
    opciones: [
      "Amazon EFS.",
      "Amazon FSx for Windows File Server.",
      "Amazon S3.",
      "Amazon FSx for Lustre.",
    ],
    correctas: [1],
    explicacion: "FSx for Windows File Server ofrece un sistema de archivos SMB nativo de Windows con integración a Active Directory. EFS es NFS (Linux); FSx for Lustre es para HPC; S3 es almacenamiento de objetos, no un file system SMB.",
  },
  {
    id: "saa-044", dominio: 2, tema: "Lambda DLQ", tipo: "single",
    enunciado: "En una arquitectura basada en colas, algunos mensajes fallan repetidamente y bloquean el procesamiento. ¿Qué mecanismo aísla esos mensajes problemáticos?",
    opciones: [
      "Aumentar el tiempo de visibilidad indefinidamente.",
      "Configurar una Dead-Letter Queue (DLQ).",
      "Eliminar la cola y recrearla.",
      "Usar SNS en lugar de SQS.",
    ],
    correctas: [1],
    explicacion: "Una Dead-Letter Queue recibe los mensajes que superan el número máximo de intentos de procesamiento, aislándolos para su análisis sin bloquear el resto de la cola. Cambiar a SNS no resuelve el manejo de mensajes fallidos.",
  },
  {
    id: "saa-045", dominio: 3, tema: "Redshift", tipo: "single",
    enunciado: "Una empresa necesita ejecutar consultas analíticas complejas (OLAP) sobre petabytes de datos históricos para reportes de negocio. ¿Qué servicio es el más adecuado?",
    opciones: [
      "Amazon RDS.",
      "Amazon DynamoDB.",
      "Amazon Redshift.",
      "Amazon ElastiCache.",
    ],
    correctas: [2],
    explicacion: "Amazon Redshift es un data warehouse columnar optimizado para consultas analíticas (OLAP) a gran escala. RDS está pensado para OLTP, DynamoDB para clave-valor y ElastiCache para caché en memoria.",
  },
  {
    id: "saa-046", dominio: 3, tema: "Athena", tipo: "single",
    enunciado: "Un equipo quiere consultar archivos de log almacenados en S3 usando SQL estándar sin cargar los datos en una base de datos ni administrar servidores. ¿Qué servicio usar?",
    opciones: [
      "Amazon Athena.",
      "Amazon RDS.",
      "AWS Glue.",
      "Amazon QuickSight.",
    ],
    correctas: [0],
    explicacion: "Amazon Athena permite consultar datos directamente en S3 con SQL, serverless y pagando por consulta. Glue es ETL; QuickSight es BI/visualización; RDS requeriría cargar los datos en una base relacional.",
  },
  {
    id: "saa-047", dominio: 2, tema: "ASG", tipo: "single",
    enunciado: "Una tienda online espera un pico de tráfico previsible cada día a las 20:00. ¿Cómo asegurar capacidad suficiente justo antes del pico minimizando costos el resto del día?",
    opciones: [
      "Mantener el máximo de instancias todo el día.",
      "Usar escalado programado (scheduled scaling) en el Auto Scaling Group.",
      "Escalar manualmente cada día.",
      "Usar solo Spot Instances.",
    ],
    correctas: [1],
    explicacion: "El escalado programado del ASG aumenta la capacidad antes de un pico previsible y la reduce después, optimizando costo y rendimiento. Mantener el máximo todo el día desperdicia dinero; el escalado manual es propenso a errores.",
  },
  {
    id: "saa-048", dominio: 1, tema: "S3 OAC", tipo: "single",
    enunciado: "Una empresa sirve contenido S3 a través de CloudFront y quiere asegurarse de que los usuarios NO puedan acceder a los objetos directamente por la URL de S3. ¿Qué configurar?",
    opciones: [
      "Hacer el bucket completamente público.",
      "Usar Origin Access Control (OAC) y restringir el bucket para que solo CloudFront pueda leerlo.",
      "Habilitar Transfer Acceleration.",
      "Usar una VPN.",
    ],
    correctas: [1],
    explicacion: "Con Origin Access Control (OAC), la política del bucket solo permite el acceso desde la distribución de CloudFront, impidiendo el acceso directo a S3. Hacer el bucket público es justo lo contrario de lo deseado.",
  },
  {
    id: "saa-049", dominio: 3, tema: "Auto Scaling", tipo: "single",
    enunciado: "Una aplicación debe mantener el uso promedio de CPU de su flota EC2 alrededor del 50%, escalando hacia arriba o abajo según la demanda real. ¿Qué política de Auto Scaling usar?",
    opciones: [
      "Target Tracking Scaling con métrica de CPU al 50%.",
      "Escalado manual.",
      "Scheduled Scaling fijo.",
      "Ninguna; usar una instancia más grande.",
    ],
    correctas: [0],
    explicacion: "Target Tracking ajusta automáticamente la cantidad de instancias para mantener una métrica objetivo (por ejemplo, CPU al 50%). El escalado programado es para patrones de tiempo conocidos, no para responder a la carga real.",
  },
  {
    id: "saa-050", dominio: 2, tema: "Route 53", tipo: "single",
    enunciado: "Una empresa quiere apuntar el dominio raíz (example.com, el apex de la zona) directamente a un Application Load Balancer. ¿Qué tipo de registro de Route 53 usar?",
    opciones: [
      "Un registro CNAME.",
      "Un registro Alias.",
      "Un registro TXT.",
      "Un registro MX.",
    ],
    correctas: [1],
    explicacion: "Los registros Alias de Route 53 permiten apuntar el apex del dominio a recursos de AWS como ALB o CloudFront (los CNAME no se permiten en el apex de la zona). TXT y MX son para verificación y correo.",
  },
  {
    id: "saa-051", dominio: 3, tema: "S3 Transfer Acceleration", tipo: "single",
    enunciado: "Usuarios de todo el mundo suben archivos grandes a un bucket S3 ubicado en us-east-1 y experimentan transferencias lentas. ¿Qué acelera estas cargas usando la red de borde de AWS?",
    opciones: [
      "S3 Transfer Acceleration.",
      "S3 Cross-Region Replication.",
      "Un NAT Gateway.",
      "S3 Lifecycle.",
    ],
    correctas: [0],
    explicacion: "S3 Transfer Acceleration usa las edge locations de CloudFront para acelerar las transferencias de larga distancia hacia/desde S3. La replicación crea copias (no acelera la subida original) y Lifecycle gestiona clases de almacenamiento.",
  },
  {
    id: "saa-052", dominio: 1, tema: "VPC Endpoint", tipo: "single",
    enunciado: "Una aplicación en una subred privada necesita invocar de forma privada APIs de un servicio AWS (por ejemplo, SQS) sin salir a Internet. ¿Qué se debe usar?",
    opciones: [
      "Un Gateway Endpoint.",
      "Un Interface Endpoint (AWS PrivateLink).",
      "Un Internet Gateway.",
      "Un Customer Gateway.",
    ],
    correctas: [1],
    explicacion: "Los Interface Endpoints (PrivateLink) crean una ENI privada en la subred para acceder a la mayoría de servicios AWS (como SQS, KMS, etc.) sin Internet. Los Gateway Endpoints solo aplican a S3 y DynamoDB.",
  },
  {
    id: "saa-053", dominio: 2, tema: "EFS", tipo: "single",
    enunciado: "Una aplicación usa EFS y la empresa quiere reducir el costo de los archivos a los que no se accede durante 30 días, sin perder el acceso compartido. ¿Qué configurar?",
    opciones: [
      "EFS Lifecycle Management para mover archivos a la clase Infrequent Access (IA).",
      "Migrar todo a EBS.",
      "Borrar los archivos antiguos.",
      "Activar Multi-Attach.",
    ],
    correctas: [0],
    explicacion: "EFS Lifecycle Management mueve automáticamente archivos no accedidos a la clase EFS Standard-IA, reduciendo costos sin perder disponibilidad. Migrar a EBS rompería el acceso compartido multi-instancia.",
  },
  {
    id: "saa-054", dominio: 3, tema: "Compute", tipo: "single",
    enunciado: "Una empresa quiere ejecutar contenedores Docker sin administrar ni aprovisionar servidores EC2 subyacentes. ¿Qué opción cumple esto?",
    opciones: [
      "Amazon ECS o EKS con el modo de lanzamiento Fargate.",
      "Amazon ECS sobre EC2 autoadministrado.",
      "Instalar Docker en EC2 manualmente.",
      "AWS Batch en EC2.",
    ],
    correctas: [0],
    explicacion: "AWS Fargate ejecuta contenedores (con ECS o EKS) sin que el cliente administre la infraestructura de servidores. Las otras opciones requieren administrar instancias EC2.",
  },
  {
    id: "saa-055", dominio: 4, tema: "Intelligent-Tiering", tipo: "single",
    enunciado: "Una empresa almacena datos en S3 cuyo patrón de acceso es desconocido y cambia con el tiempo. Quieren optimizar costos sin riesgo de cargos por recuperación ni esfuerzo manual. ¿Qué clase usar?",
    opciones: [
      "S3 Standard.",
      "S3 Intelligent-Tiering.",
      "S3 One Zone-IA.",
      "S3 Glacier Deep Archive.",
    ],
    correctas: [1],
    explicacion: "S3 Intelligent-Tiering mueve automáticamente los objetos entre niveles de acceso según el uso, sin cargos por recuperación ni gestión manual, ideal cuando el patrón es impredecible. Standard-IA/One Zone-IA cobran por recuperación si te equivocás de patrón.",
  },
  {
    id: "saa-056", dominio: 2, tema: "Multi-AZ RDS", tipo: "single",
    enunciado: "Durante el mantenimiento o un fallo de hardware del nodo primario de RDS Multi-AZ, ¿qué sucede con la conexión de la aplicación?",
    opciones: [
      "La aplicación debe cambiar manualmente la IP de la base de datos.",
      "RDS hace failover automático al standby y el endpoint DNS apunta al nuevo primario.",
      "La base de datos queda inaccesible hasta restaurar un snapshot.",
      "Se pierde toda la data desde el último backup.",
    ],
    correctas: [1],
    explicacion: "En Multi-AZ, RDS promueve automáticamente la réplica standby y actualiza el registro DNS del endpoint, por lo que la aplicación se reconecta sin cambios manuales. No hay que restaurar snapshots ni se pierde data por el failover.",
  },
  {
    id: "saa-057", dominio: 3, tema: "CloudFront", tipo: "single",
    enunciado: "Para reducir la carga sobre los servidores de origen y mejorar el rendimiento de un sitio dinámico, una empresa quiere cachear respuestas y ejecutar lógica ligera cerca del usuario. ¿Qué combinación usar?",
    opciones: [
      "CloudFront con políticas de caché y funciones en el borde (CloudFront Functions / Lambda@Edge).",
      "Solo un Application Load Balancer.",
      "Route 53 con failover.",
      "Un NAT Gateway por región.",
    ],
    correctas: [0],
    explicacion: "CloudFront cachea contenido en el borde y, con CloudFront Functions o Lambda@Edge, ejecuta lógica liviana cerca del usuario, reduciendo latencia y carga del origen. Un ALB o Route 53 por sí solos no cachean en el borde.",
  },
  {
    id: "saa-058", dominio: 1, tema: "Shield", tipo: "single",
    enunciado: "Una aplicación pública crítica necesita protección avanzada contra ataques DDoS de gran escala, con soporte y mitigación gestionada 24/7. ¿Qué servicio contratar?",
    opciones: [
      "AWS Shield Standard.",
      "AWS Shield Advanced.",
      "AWS WAF únicamente.",
      "Amazon GuardDuty.",
    ],
    correctas: [1],
    explicacion: "AWS Shield Advanced ofrece protección DDoS mejorada, detección y mitigación gestionada, acceso al equipo de respuesta DDoS y protección de costos. Shield Standard es automático y gratuito pero básico; WAF filtra capa 7 pero no es específicamente anti-DDoS volumétrico.",
  },
  {
    id: "saa-059", dominio: 2, tema: "Step Functions", tipo: "single",
    enunciado: "Una empresa necesita orquestar un flujo de trabajo de varios pasos con reintentos, manejo de errores y ramificaciones entre varias funciones Lambda. ¿Qué servicio coordina esto?",
    opciones: [
      "Amazon SQS.",
      "AWS Step Functions.",
      "Amazon EventBridge Scheduler.",
      "AWS Glue.",
    ],
    correctas: [1],
    explicacion: "AWS Step Functions orquesta flujos de trabajo serverless con estados, reintentos, manejo de errores y ramificaciones, coordinando múltiples Lambdas y servicios. SQS solo encola mensajes; no orquesta el flujo.",
  },
  {
    id: "saa-060", dominio: 3, tema: "EBS tipos", tipo: "single",
    enunciado: "Una base de datos transaccional requiere un volumen EBS con IOPS muy altas y consistentes, y alta durabilidad. ¿Qué tipo de volumen elegir?",
    opciones: [
      "gp2 (SSD de propósito general).",
      "io2 / io2 Block Express (SSD de IOPS provisionadas).",
      "st1 (HDD optimizado para throughput).",
      "sc1 (HDD frío).",
    ],
    correctas: [1],
    explicacion: "Los volúmenes io2/io2 Block Express ofrecen IOPS provisionadas altas y consistentes con gran durabilidad, ideales para bases de datos de alto rendimiento. Los HDD (st1/sc1) priorizan throughput/costo, no IOPS.",
  },
  {
    id: "saa-061", dominio: 4, tema: "Savings Plans", tipo: "single",
    enunciado: "Una empresa usa una mezcla de EC2, Fargate y Lambda con un gasto base constante y quiere ahorrar con la mayor flexibilidad entre estos servicios. ¿Qué opción de precios elegir?",
    opciones: [
      "EC2 Instance Savings Plans solamente.",
      "Compute Savings Plans.",
      "Reserved Instances estándar.",
      "On-Demand para todo.",
    ],
    correctas: [1],
    explicacion: "Los Compute Savings Plans aplican el descuento a EC2, Fargate y Lambda con flexibilidad de familia, región y servicio, ideal para una carga base mixta. Las RIs estándar y los EC2 Instance Savings Plans son menos flexibles.",
  },
  {
    id: "saa-062", dominio: 2, tema: "S3 versioning", tipo: "single",
    enunciado: "Para protegerse contra sobrescrituras y borrados accidentales de objetos en un bucket S3 y poder recuperar versiones anteriores, ¿qué se debe habilitar?",
    opciones: [
      "S3 Versioning.",
      "S3 Transfer Acceleration.",
      "S3 Block Public Access.",
      "S3 Storage Lens.",
    ],
    correctas: [0],
    explicacion: "El versionado conserva versiones anteriores de cada objeto, permitiendo recuperar o revertir tras borrados/sobrescrituras accidentales. Block Public Access controla acceso público y Storage Lens da métricas de uso.",
  },
  {
    id: "saa-063", dominio: 3, tema: "Placement Groups", tipo: "single",
    enunciado: "Una aplicación HPC requiere comunicación de red de muy baja latencia y alto throughput entre instancias EC2 dentro de la misma AZ. ¿Qué configuración de colocación usar?",
    opciones: [
      "Cluster Placement Group.",
      "Spread Placement Group.",
      "Partition Placement Group.",
      "Instancias en distintas regiones.",
    ],
    correctas: [0],
    explicacion: "Un Cluster Placement Group agrupa instancias físicamente cercanas en una AZ para lograr la menor latencia y el mayor throughput de red, ideal para HPC. Spread y Partition priorizan disponibilidad/aislamiento, no latencia mínima.",
  },
  {
    id: "saa-064", dominio: 1, tema: "IAM Policy", tipo: "single",
    enunciado: "Siguiendo el principio de mínimo privilegio, ¿cuál es la mejor práctica al crear políticas IAM para un nuevo servicio?",
    opciones: [
      "Otorgar permisos de administrador para evitar problemas.",
      "Conceder únicamente los permisos específicos que la tarea necesita y ampliarlos solo si hace falta.",
      "Usar siempre la cuenta root.",
      "Compartir una sola clave de acceso entre todos los servicios.",
    ],
    correctas: [1],
    explicacion: "El principio de mínimo privilegio recomienda otorgar solo los permisos estrictamente necesarios y ampliarlos si se requiere. Dar permisos de administrador o usar root amplía innecesariamente la superficie de ataque.",
  },
  {
    id: "saa-065", dominio: 2, tema: "Snapshot DR", tipo: "single",
    enunciado: "Una empresa quiere copias de seguridad automáticas y de bajo costo de sus volúmenes EBS, replicadas a otra región para recuperación ante desastres. ¿Qué combinación usar?",
    opciones: [
      "Data Lifecycle Manager para snapshots automáticos + copia de snapshots cross-region.",
      "Convertir EBS en Instance Store.",
      "Subir manualmente los datos a S3 cada semana.",
      "Usar solo Multi-AZ.",
    ],
    correctas: [0],
    explicacion: "Amazon Data Lifecycle Manager automatiza la creación y retención de snapshots de EBS, que luego pueden copiarse a otra región para DR. Multi-AZ no protege contra la caída de una región completa.",
  },
  {
    id: "saa-066", dominio: 3, tema: "Lambda límites", tipo: "single",
    enunciado: "Un proceso de transformación de datos tarda alrededor de 25 minutos en completarse. ¿Por qué AWS Lambda NO es adecuado y qué alternativa conviene?",
    opciones: [
      "Lambda no tiene límite de tiempo; es adecuado.",
      "Lambda tiene un límite de 15 minutos por ejecución; conviene usar contenedores en ECS/Fargate o AWS Batch.",
      "Lambda solo corre 1 minuto; usar EC2 nano.",
      "Lambda no soporta Python; usar Glue.",
    ],
    correctas: [1],
    explicacion: "Lambda tiene un tiempo máximo de ejecución de 15 minutos, por lo que un proceso de 25 minutos debe ejecutarse en ECS/Fargate, AWS Batch o EC2. El resto de afirmaciones sobre límites/lenguajes son incorrectas.",
  },
  {
    id: "saa-067", dominio: 2, tema: "Aurora Global", tipo: "single",
    enunciado: "Una empresa global necesita una base de datos relacional con réplica en otra región para recuperación ante desastres con RPO bajo y lecturas locales rápidas. ¿Qué solución usar?",
    opciones: [
      "Amazon Aurora Global Database.",
      "RDS single-AZ con snapshots manuales.",
      "DynamoDB con TTL.",
      "Una réplica de lectura dentro de la misma AZ.",
    ],
    correctas: [0],
    explicacion: "Aurora Global Database replica los datos a otras regiones con baja latencia (RPO típicamente segundos) y permite lecturas locales y promoción rápida ante un desastre regional. Una réplica en la misma AZ no protege contra fallos regionales.",
  },
  {
    id: "saa-068", dominio: 1, tema: "MFA", tipo: "multiple",
    enunciado: "¿Cuáles de las siguientes son buenas prácticas de seguridad para la cuenta AWS? (Elegí 2).",
    opciones: [
      "Habilitar MFA en la cuenta root y en usuarios privilegiados.",
      "Usar la cuenta root para las operaciones diarias.",
      "Aplicar el principio de mínimo privilegio en las políticas IAM.",
      "Compartir las credenciales root con todo el equipo.",
    ],
    correctas: [0, 2],
    explicacion: "Habilitar MFA y aplicar mínimo privilegio son prácticas recomendadas. La cuenta root no debe usarse para tareas diarias ni compartirse; se usan usuarios/roles IAM con permisos acotados.",
  },
  {
    id: "saa-069", dominio: 3, tema: "Outposts", tipo: "single",
    enunciado: "Una empresa necesita ejecutar servicios de AWS en su propio centro de datos local para cumplir requisitos de baja latencia y residencia de datos. ¿Qué servicio usar?",
    opciones: [
      "AWS Outposts.",
      "Amazon CloudFront.",
      "AWS Direct Connect.",
      "Amazon EC2 en us-east-1.",
    ],
    correctas: [0],
    explicacion: "AWS Outposts lleva infraestructura y servicios de AWS al centro de datos del cliente (on-premises), útil para baja latencia local y residencia de datos. Direct Connect es solo conectividad de red, no cómputo local.",
  },
  {
    id: "saa-070", dominio: 2, tema: "SQS visibility", tipo: "single",
    enunciado: "Algunos mensajes en una cola SQS se procesan más de una vez porque el consumidor tarda más que el tiempo de visibilidad. ¿Qué ajustar para evitarlo?",
    opciones: [
      "Aumentar el Visibility Timeout para que cubra el tiempo de procesamiento.",
      "Reducir el Visibility Timeout a cero.",
      "Eliminar la cola.",
      "Cambiar a SNS.",
    ],
    correctas: [0],
    explicacion: "Si el procesamiento tarda más que el Visibility Timeout, el mensaje vuelve a estar visible y otro consumidor lo toma. Aumentar el timeout (o renovarlo) evita el reprocesamiento. Reducirlo a cero empeora el problema.",
  },
  {
    id: "saa-071", dominio: 4, tema: "Fargate vs EC2", tipo: "single",
    enunciado: "Una startup ejecuta contenedores con carga variable y quiere evitar pagar por capacidad ociosa y no administrar servidores. ¿Qué opción minimiza costo operativo?",
    opciones: [
      "ECS sobre una flota EC2 sobredimensionada.",
      "ECS/EKS sobre Fargate, pagando por los recursos que consumen las tareas.",
      "EC2 On-Demand grande encendido 24/7.",
      "Dedicated Hosts.",
    ],
    correctas: [1],
    explicacion: "Fargate cobra por la vCPU y memoria que consumen las tareas, sin administrar ni pagar servidores ociosos, ideal para cargas variables. Una flota EC2 sobredimensionada o instancias 24/7 desperdician dinero.",
  },
  {
    id: "saa-072", dominio: 3, tema: "Read Replica cross-region", tipo: "single",
    enunciado: "Usuarios en Europa sufren alta latencia al leer de una base de datos RDS ubicada en EE. UU. ¿Cómo mejorar el rendimiento de lectura para esos usuarios?",
    opciones: [
      "Crear una Read Replica de RDS en la región europea y dirigir las lecturas allí.",
      "Aumentar el almacenamiento de la base de datos.",
      "Habilitar Multi-AZ en EE. UU.",
      "Migrar a Instance Store.",
    ],
    correctas: [0],
    explicacion: "Una Read Replica cross-region en Europa acerca los datos de lectura a los usuarios locales, reduciendo la latencia. Multi-AZ mejora disponibilidad pero no acerca los datos a otra región; más almacenamiento no afecta la latencia geográfica.",
  },
  {
    id: "saa-073", dominio: 1, tema: "GuardDuty", tipo: "single",
    enunciado: "Una empresa quiere detección continua e inteligente de amenazas (actividad maliciosa, comportamiento anómalo) analizando CloudTrail, VPC Flow Logs y DNS logs, sin desplegar agentes. ¿Qué servicio usar?",
    opciones: [
      "Amazon GuardDuty.",
      "AWS WAF.",
      "Amazon Inspector.",
      "AWS Config.",
    ],
    correctas: [0],
    explicacion: "GuardDuty analiza fuentes como CloudTrail, VPC Flow Logs y DNS logs para detectar amenazas y comportamientos anómalos, sin agentes. Inspector evalúa vulnerabilidades de instancias; WAF filtra tráfico web; Config evalúa configuración.",
  },
  {
    id: "saa-074", dominio: 2, tema: "EventBridge", tipo: "single",
    enunciado: "Una arquitectura orientada a eventos necesita enrutar eventos de distintos servicios AWS y aplicaciones SaaS a múltiples destinos según reglas de coincidencia. ¿Qué servicio usar?",
    opciones: [
      "Amazon EventBridge.",
      "Amazon SQS Standard.",
      "AWS Direct Connect.",
      "Amazon Kinesis Firehose.",
    ],
    correctas: [0],
    explicacion: "Amazon EventBridge es un bus de eventos serverless que enruta eventos de servicios AWS, aplicaciones propias y SaaS hacia múltiples destinos según reglas. SQS es una cola punto a punto; Firehose entrega streaming a destinos de almacenamiento.",
  },
  {
    id: "saa-075", dominio: 3, tema: "Storage Gateway", tipo: "single",
    enunciado: "Una empresa con almacenamiento on-premises quiere extender su capacidad a la nube de forma transparente, manteniendo acceso local de baja latencia a los datos usados con frecuencia. ¿Qué servicio usar?",
    opciones: [
      "AWS Storage Gateway.",
      "Amazon S3 directamente desde las apps locales.",
      "AWS Snowmobile.",
      "Amazon EFS montado por Internet.",
    ],
    correctas: [0],
    explicacion: "AWS Storage Gateway integra el almacenamiento on-premises con la nube (File/Volume/Tape Gateway), cacheando localmente los datos frecuentes y respaldando el resto en AWS. Snowmobile es para migraciones masivas únicas, no acceso híbrido continuo.",
  },
  {
    id: "saa-076", dominio: 4, tema: "Lambda costo", tipo: "single",
    enunciado: "Una API recibe tráfico muy esporádico (unas pocas solicitudes por hora). ¿Qué arquitectura minimiza el costo evitando pagar por servidores inactivos?",
    opciones: [
      "API Gateway + AWS Lambda (serverless, pago por solicitud).",
      "Una instancia EC2 t3.medium encendida 24/7.",
      "Un clúster EKS con 3 nodos.",
      "Un ALB con dos instancias siempre activas.",
    ],
    correctas: [0],
    explicacion: "Para tráfico esporádico, API Gateway + Lambda cobra por solicitud y tiempo de ejecución, sin costo en reposo, minimizando el gasto. Mantener EC2/EKS/ALB activos 24/7 genera costo aunque no haya tráfico.",
  },
  {
    id: "saa-077", dominio: 2, tema: "Cross-AZ", tipo: "single",
    enunciado: "Una aplicación stateless corre en EC2 detrás de un ALB. ¿Qué medida garantiza que siga operando si una zona de disponibilidad completa falla?",
    opciones: [
      "Distribuir las instancias en al menos dos AZ dentro del Auto Scaling Group.",
      "Usar una instancia más potente en una sola AZ.",
      "Guardar la sesión en disco local.",
      "Apagar el ALB durante el fallo.",
    ],
    correctas: [0],
    explicacion: "Desplegar el ASG en dos o más AZ permite que el tráfico siga atendiéndose desde las AZ sanas si una falla. Concentrar todo en una AZ deja la app sin servicio cuando esa zona cae.",
  },
  {
    id: "saa-078", dominio: 1, tema: "S3 cifrado en tránsito", tipo: "single",
    enunciado: "Una política de seguridad exige que todas las conexiones a un bucket S3 usen cifrado en tránsito (HTTPS/TLS) y rechazar las que no. ¿Cómo se logra?",
    opciones: [
      "Con una bucket policy que deny cuando aws:SecureTransport sea false.",
      "Activando el versionado.",
      "Con una NACL en la VPC.",
      "Usando una clave de acceso más larga.",
    ],
    correctas: [0],
    explicacion: "Una bucket policy puede denegar el acceso cuando la condición aws:SecureTransport es false, forzando HTTPS/TLS. El versionado, las NACL o el tamaño de la clave no controlan el cifrado en tránsito hacia S3.",
  },
  {
    id: "saa-079", dominio: 3, tema: "DynamoDB capacidad", tipo: "single",
    enunciado: "Una nueva aplicación tendrá un patrón de tráfico totalmente impredecible en DynamoDB y el equipo no quiere planificar capacidad. ¿Qué modo de capacidad elegir?",
    opciones: [
      "On-Demand capacity mode.",
      "Provisioned con valores bajos fijos.",
      "Provisioned sin Auto Scaling.",
      "Reserved Capacity a 3 años.",
    ],
    correctas: [0],
    explicacion: "El modo On-Demand de DynamoDB se adapta automáticamente a cualquier nivel de tráfico sin planificar capacidad, ideal para cargas nuevas o impredecibles. Provisioned fijo puede quedar corto o desperdiciar capacidad.",
  },
  {
    id: "saa-080", dominio: 2, tema: "Health checks", tipo: "single",
    enunciado: "Un Application Load Balancer sigue enviando tráfico a instancias que están fallando. ¿Qué se debe configurar para que solo se enrute a instancias sanas?",
    opciones: [
      "Health checks del target group para que el ALB deje de enviar tráfico a instancias no saludables.",
      "Aumentar el timeout del ALB.",
      "Quitar el ALB.",
      "Usar IP públicas en todas las instancias.",
    ],
    correctas: [0],
    explicacion: "Los health checks permiten al ALB detectar instancias no saludables y dejar de enrutar tráfico hacia ellas (y, con un ASG, reemplazarlas). Sin health checks bien configurados, el LB sigue enviando tráfico a instancias caídas.",
  },
]);
